config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#home'
  
  resources :articles
  
  get 'about', to: 'welcome#about'
  
  get 'signup',to: 'users#new'
  
  get 'login',to: 'sessions#new'
  
  post 'login',to: 'sessions#create'
  
  delete 'logout',to: 'sessions#destroy'
  
  resources :users, except:[:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title,presence:true,length: {minimum:3,maximum:500}
    validates :description,presence:true,length: {minimum:10,maximum:3000}
    validates :user_id,presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    validates :username,presence: true,length: {minimum:3,maximum:25},uniqueness: {case_sensitive: false}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,presence: true,length: {maximum:100},uniqueness: {case_sensitive: false},
                    format: { with: VALID_EMAIL_REGEX}
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  
  def current_user
    @current_user||= User.find(session[:user_id]) if session[:user_id]
    
  end
  
  def logged_in?
    
    !!current_user
    
  end
  
  def required_user
    
    if !logged_in?
      
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
      
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :get_param, only: [:edit,:update,:destroy,:show]
    before_action :required_user, except: [:show,:index]
    before_action :required_same_user, only: [:edit,:update,:destroy]
    def new
        @article = Article.new
    end
    
    def edit
    end
    
    def destroy
       @article.destroy
       flash[:danger] = "Article was successfully deleted"
       redirect_to articles_path
    end
    
    def index
       
       @articles=Article.paginate(page: params[:page], per_page: 5)
       
    end
    
    def update
        
        if @article.update(article_params)
            
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)
            
        else
            
            render 'edit'
        
        end
        
    end
    
    
    def create

        @article = Article.new(article_params)
        @article.user=User.first
        
        if @article.save
           
           flash[:success] = "Article was successfully added"
           redirect_to article_path(@article)
           
        else
           
           render 'new'
        
        end

    end
 
    def show
        
    end
    
    private
    
    def get_param
        
        @article = Article.find(params[:id])
     
         
    end
    

    def article_params

        params.require(:article).permit(:title, :description)

    end
    
    def required_same_user
        
        if @article.user != current_user && !current_user.admin?
            
            flash[:danger] = "You can delete and update your own articles"
            redirect_to root_path
            
        end
        
    end
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   
   def new
   
   end
   
   def create
       user=User.find_by(email: params[:session][:email].downcase)
       if user && user.authenticate(params[:session][:password])
           session[:user_id] = user.id
           flash[:success] = "You have successfully logged in"
           redirect_to user_path(user)
       else
           flash.now[:danger] = "Email id or password is wrong"
           render 'new'
       end
   end
   
   def destroy
       
       session[:user_id] = nil
       flash[:success] = "You have logged out"
       redirect_to root_path
       
   end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :get_user, only: [:edit,:update,:show]
    
    before_action :required_same_user, only: [:edit,:update,:destroy]
    
    before_action :required_admin, only: [:destroy]
    
    def new
        
        @user=User.new
        
        
    end
    
    def index
       @users=User.paginate(page: params[:page],per_page: 2) 
    end
    
    def show
       
       @user_articles=@user.articles.paginate(page: params[:page], per_page: 1)
        
    end
    
    def create
       @user = User.new(user_params)
       if @user.save
           session[:user_id] = @user.id
           flash[:success]="Welcome to the AlphaBlog"
           
           redirect_to articles_path
           
       else
           
           render 'new'
           
       end
        
    end
    
    def edit
       
    end
    
    def destroy
        
        @user=User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all their articles have been deleted"
        redirect_to users_path
        
    end
    
    def update
       if @user.update(user_params)
           flash[:success]="Account has been successfully updated"
           redirect_to articles_path
           
       else
           render 'edit'
           
       end
    end
    
    private
    
    def user_params
        
        params.require(:user).permit(:username,:email,:password)
        
    end
    
    def get_user
        @user=User.find(params[:id])
    end
    
    def required_same_user
        
        if @user != current_user && !current_user.admin?
            flash[:danger] = "You can edit your own account only"
            redirect_to root_path
            
        end
        
    end
    
    def required_admin
        
        if !logged_in? && !current_user.admin?
            
            flash[:danger] = "Only admin user can perform this action"
            redirect_to root_path
            
        end
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
        
    end
    
    def about
        
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user,options = {size:80})
        
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)

        size = options[:size]

        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

        image_tag(gravatar_url, alt: user.username, class: "img-circle")

    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="well well-rg">
                    <div class="article-tite">
                        <%= link_to article.title,article_path(article) %>
                    </div>
                    <div class="article-description">
                        <%= truncate(article.description,length:50) %>
                        <div class="article-user-metadata">
                            <small> Created by: <%= article.user.username if article.user%>,
                            <%= time_ago_in_words(article.created_at) %> ago,
                            last_updated: <%= time_ago_in_words(article.updated_at) %> ago </small>
                        </div>
                            </small>
                            
                    </div>
                    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                        <div class="article-actions">
                            <%= link_to "Edit this article",edit_article_path(article),class: "btn btn-xs btn-primary" %>
                            <%= link_to "Delete this article",article_path(article),method: :delete,
                                                                                    data: {Confirm:"Are you sure you want to delete this article?"},
                                                                                    class: "btn btn-xs btn-danger" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class='row'>
    
    <div class='col-xs-12'>

        <%= form_for(@article,:html => {class:"form-horizontal",role:"form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                
                <div class="col-sm-8">
                    <%= f.text_field :title, class:"form-control",placeholder:"Title of Article",autofocus:true %>
                </div>
            </div>
        
        
            <div class="form-group">
                <div class="control-label col-sm-2">
                    
                    <%= f.label :description %><br/><br/>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows:10,class:"form-control",placeholder:"Description of Article",autofocus:true %><br/>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class:'btn btn-primary btn-lg'%>
                </div>
            </div>
        <% end %>
        
            <div class="col-xs-4 col-xs-offset-4">
               [<%= link_to "Cancel request and return to listing articles",articles_path %>]
            </div>

</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">  Edit existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2 align="Center"> Listing all Articles</h2>
<div class="center">
    <%= will_paginate %>
</div>
 <%= render 'article', obj: @articles %>
 
 <div class="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align='center'>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title: <%= @article.title %> </h2>
<div class="well col-xs-8 col-xs-offset-2">
<% if @article.user %>

 <ul class="listing">
    <div class="row center">
        <div class="col-md-4 col-md-offset-4">
            <li> Created by:</li>
            <li><%=link_to gravatar_for(@article.user),user_path(@article.user)%></li>
            <li class="article-title"> <%= link_to @article.user.username,user_path(@article.user) %> </li>
            <li><small><%= pluralize(@article.user.articles.count,'article') if @article.user.articles %></small></li>
        </div>
    </div>
    </ul>
<% end %>

    <h4 class="center description"> <strong> Description: </strong> </h4>
    <hr>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
        
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        
            <%= link_to "Edit this article",edit_article_path(@article),class: "btn btn-primary btn-xs" %>
            <%= link_to "Delete this article",article_path(@article),method: :delete,
                                                                    data: {Confirm: "Are you sure you want to delete this article?"},
                                                                    class:"btn btn-xs btn-danger" %>
                                                                    
        <% end %>  
        <%= link_to "View all articles",articles_path,class:"btn btn-xs btn-success" %>
        
    </div>
</div>

app/views/layouts/_flash.html.erb
<div class="row">
<div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name,msg| %>
   <div class='alert alert-<%="#{name}"%>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
   </div>
  <% end %>
 </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
             Copyright © <a href="https://www.ziggletech.com">Ziggle Tech Inc Ltd</a>
             by <a href="https://www.ziggletech.com"> Chetan Joshi</a>
        </small>
        <nav>
            <ul>
                <li> <%= link_to "About",about_path %> </li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog",root_path,class: "navbar-brand",id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles",articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article",new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View your profile', user_path(current_user) %> </li>
              <li><%= link_to 'Edit your profile', edit_user_path(current_user) %> </li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/navigation' %>
 <%= render 'layouts/flash' %> 
 <div class="container">
 <%= yield %>
 </div>
 <%= render 'layouts/footer' %>
 

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%=pluralize(obj.errors.count,"error")%>
                    prohibited this article from being saved:
                </h2>
                <div class="panel-body">
                    <ul>
                        <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                        <%end%>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class='row'>
    
    <div class='col-xs-12'>

        <%= form_for(@user,:html => {class:"form-horizontal",role:"form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :username %>
                </div>
                
                <div class="col-sm-8">
                    <%= f.text_field :username, class:"form-control",placeholder:"Enter username",autofocus:true %>
                </div>
            </div>
        
        
            <div class="form-group">
                <div class="control-label col-sm-2">
                    
                    <%= f.label :email %><br/><br/>
                </div>
                <div class="col-sm-8">
                    <%= f.email_field :email, rows:10,class:"form-control",placeholder:"Enter email",autofocus:true %><br/>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    
                    <%= f.label :password %><br/><br/>
                </div>
                <div class="col-sm-8">
                    <%= f.password_field :password, rows:10,class:"form-control",placeholder:"Enter password",autofocus: true,autocomplete: false %><br/>
                </div>
            </div>            
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit(@user.new_record? ? "Signup" : "Update account", class:'btn btn-primary btn-lg')%>
                </div>
            </div>
        <% end %>
        
            <div class="col-xs-4 col-xs-offset-4">
               [<%= link_to "Cancel request and return to listing articles",articles_path %>]
            </div>

</div>
</div>

app/views/users/edit.html.erb
<h1 align="center"> Edit your account </h1>
 <%= render 'form' %>

app/views/users/index.html.erb
<h1 align='Center'> Showing all users </h1>

<div align="center">
    <%= will_paginate %>
 <% @users.each do |user| %>
    <ul class="listing">
    <div class="row">
        <div class="well col-md-4 col-md-offset-4">
            <li><%=link_to gravatar_for(user),user_path(user)%></li>
            <li class="article-title"> <%= link_to user.username,user_path(user) %> </li>
            <li><small><%= pluralize(user.articles.count,'article') if user.articles %></small></li>
            <% if logged_in? and current_user.admin? %>
                <li> <%= link_to "Delete user", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user and all their articles"} %></li>
            <% end %>
        </div>
    </div>
    </ul>
 <% end %>
 
 <%= will_paginate %>
 
</div>

app/views/users/new.html.erb
<h1 align="center"> Signup for AlphaBlog </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s Page</h1>

<div class="row">
    
    <div class="col-md-4 col-md-offset-4 center">
        
        <%= gravatar_for @user,size:150 %>
        
        
        
    </div>
    
</div>

<h4 align="center"><%= @user.username%>'s articles</h4>

<div class="center">
    <%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj: @user_articles %>

<div class="center">
    <%= will_paginate @user_articles %>
</div>

app/views/welcome/about.html.erb
<h1> This is the about page</h1>

<%= link_to 'Home',root_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
    <h1> ALPHA BLOG</h1>
    <%= link_to "Sign up now",signup_path,class:"btn btn-primary btn-lg" %>
</div>